---
AllCops:
  DisabledByDefault: false
  NewCops: enable
  StyleGuideCopsOnly: false

Metrics/BlockLength:
  AllowedPatterns: ["describe", "context"]

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
